server:
  port: 8086
eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    #服务在注册中心的名称 不同服务名称不能重复
    name: cloud-feign
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: my-application
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: 1906B
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



