
server:
  port: 8084
eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    #服务在注册中心的名称 不同服务名称不能重复
    name: cloud-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/home?useUnicode=true&characterEncoding=utf-8
    username: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*.xml
